### ISSUE TITLE
Error on RSpec/FilePath in rubocop-rspec 1.43.0

### ISSUE THREAD

**Issue by single-stop-tony** [rubocop-hq/rubocop-rspec#1003]
Receiving the following error (repeated over ten times) when attempting to run rubocop on rubocop-rspec 1.43.0

```
An error occurred while RSpec/FilePath cop was inspecting ~/project/app/helpers/api_helper.rb.
undefined method `begin_type?' for nil:NilClass
~/.rvm/gems/ruby-2.7.0/gems/rubocop-rspec-1.43.0/lib/rubocop/rspec/top_level_group.rb:41:in `top_level_nodes'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-rspec-1.43.0/lib/rubocop/rspec/top_level_group.rb:44:in `top_level_nodes'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-rspec-1.43.0/lib/rubocop/rspec/top_level_group.rb:26:in `top_level_groups'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-rspec-1.43.0/lib/rubocop/rspec/top_level_group.rb:18:in `on_new_investigation'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:103:in `block (2 levels) in invoke'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:112:in `with_cop_error_handling'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:102:in `block in invoke'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:101:in `each'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:101:in `invoke'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/commissioner.rb:72:in `investigate'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/team.rb:151:in `investigate_partial'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cop/team.rb:83:in `investigate'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:295:in `inspect_file'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:245:in `block in do_inspection_loop'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:277:in `block in iterate_until_no_changes'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:270:in `loop'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:270:in `iterate_until_no_changes'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:241:in `do_inspection_loop'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:121:in `block in file_offenses'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:146:in `file_offense_cache'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:120:in `file_offenses'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:111:in `process_file'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:90:in `block in each_inspected_file'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:89:in `each'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:89:in `reduce'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:89:in `each_inspected_file'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:78:in `inspect_files'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/runner.rb:39:in `run'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli/command/execute_runner.rb:21:in `execute_runner'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli/command/execute_runner.rb:13:in `run'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli/command.rb:10:in `run'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli/environment.rb:17:in `run'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli.rb:65:in `run_command'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli.rb:72:in `execute_runners'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/lib/rubocop/cli.rb:41:in `run'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/exe/rubocop:13:in `block in <top (required)>'
~/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
~/.rvm/gems/ruby-2.7.0/gems/rubocop-0.89.1/exe/rubocop:12:in `<top (required)>'
~/.rvm/gems/ruby-2.7.0/bin/rubocop:23:in `load'
~/.rvm/gems/ruby-2.7.0/bin/rubocop:23:in `<main>'
~/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `eval'
~/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:24:in `<main>'
```

RuboCop -V: 0.89.1 (using Parser 2.7.1.4, rubocop-ast 0.3.0, running on ruby 2.7.0 x86_64-darwin19)

**Comment by single-stop-tony** [comment]
Woops, just saw that this was fixed in a later patch
