### ISSUE TITLE
RSpec/DescribedClass (undefined method `first' for nil:NilClass described_class.rb:175)

### ISSUE THREAD

**Issue by CaptainPhilipp** [rubocop-hq/rubocop-rspec#1038]
My spec:
```
module Namespace1
  module Namespace2
    module Namespace3
      RSpec.describe MyClass do
```

For class
```
Namespace1::Namespace2::Namespace3::MyClass
```

Backtrace:
```
An error occurred while RSpec/DescribedClass cop was inspecting .../namespace1/namespace2/namespace3/delete_user_spec.rb:6:6.
undefined method `first' for nil:NilClass
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:175:in `collapse_namespace'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:160:in `full_const_name'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:156:in `offensive_described_class?'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:140:in `offensive?'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:106:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:111:in `block in find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:110:in `find_usage'
.../ruby-2.6.5@my_gemset/gems/rubocop-rspec-1.41.0/lib/rubocop/cop/rspec/described_class.rb:87:in `on_block'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:128:in `with_cop_error_handling'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:150:in `on_while'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:150:in `on_while'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:150:in `on_while'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:13:in `walk'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:119:in `investigate'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:107:in `offenses'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:277:in `inspect_file'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:225:in `block in do_inspection_loop'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:257:in `block in iterate_until_no_changes'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `loop'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `iterate_until_no_changes'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:221:in `do_inspection_loop'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:142:in `file_offense_cache'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:122:in `file_offenses'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:110:in `process_file'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `reduce'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:73:in `inspect_files'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/runner.rb:39:in `run'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cli.rb:210:in `execute_runner'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cli.rb:80:in `execute_runners'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/lib/rubocop/cli.rb:51:in `run'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/exe/rubocop:13:in `block in <top (required)>'
.../.rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
.../ruby-2.6.5@my_gemset/gems/rubocop-0.74.0/exe/rubocop:12:in `<top (required)>'
.../ruby-2.6.5@my_gemset/bin/rubocop:23:in `load'
.../ruby-2.6.5@my_gemset/bin/rubocop:23:in `<main>'
.../ruby-2.6.5@my_gemset/bin/ruby_executable_hooks:24:in `eval'
.../ruby-2.6.5@my_gemset/bin/ruby_executable_hooks:24:in `<main>'

...

Mention the following information in the issue report:
0.74.0 (using Parser 2.6.3.0, running on ruby 2.6.5 x86_64-darwin18)
```

Debug:
```
undefined method `first' for nil:NilClass described_class.rb:175:in `collapse_namespace'
```
```
173        def collapse_namespace(namespace, const)
174          return const if namespace.empty?
175          return const if const.first.nil?
176
177          start = [0, (namespace.length - const.length)].max
178          max = namespace.length
179          intersection = (start..max).find do |shift|
180            namespace[shift, max - shift] == const[0, max - shift]
181          end
182          [*namespace[0, intersection], *const]
183        end
```

When exception raises,
argument `namespace` equals `[:Namespace1, :Namespace2, :Namespace3]`
argument `const` is `nil`

**Comment by pirj** [comment]
I can't reproduce with just:
```ruby
module Namespace1
  module Namespace2
    module Namespace3
      RSpec.describe MyClass do
      end
    end
  end
end
```

Can you please confirm the above code results in a failure as well, or otherwise provide a minimum reproduction example?

**Comment by pirj** [comment]
Just in case, your `EnforcedStyle` setting is `described_class`, correct?

**Comment by CaptainPhilipp** [comment]
Also i've found that there are two rules:
`RSpec/DescribedClass`
`RSpec/DescribeClass`

first is falling, second works fine

**Comment by pirj** [comment]
Those two are completely different cops.

**Comment by CaptainPhilipp** [comment]
> Just in case, your `EnforcedStyle` setting is `described_class`, correct?

Mm, idk. What do you mean or where I can see it?

**Comment by CaptainPhilipp** [comment]
> Just in case, your `EnforcedStyle` setting is `described_class`, correct?

If you mean some rule named EnforcedStyle - it's not shadowed and should be default

**Comment by CaptainPhilipp** [comment]
> I can't reproduce with just:
> 
> ```ruby
> module Namespace1
>   module Namespace2
>     module Namespace3
>       RSpec.describe MyClass do
>       end
>     end
>   end
> end
> ```
> 
> Can you please confirm the above code results in a failure as well, or otherwise provide a minimum reproduction example?

MyClass is `Namespace1::Namespace2::Namespace3::MyClass` ?

**Comment by pirj** [comment]
So you mention that `collapse_namespace`'s
> argument `const` is `nil`

`collapse_namespace` is called with an argument value that is returned by `const_name(node)`, which is:
```ruby
        def const_name(node)
          # rubocop:disable InternalAffairs/NodeDestructuring
          namespace, name = *node
          # rubocop:enable InternalAffairs/NodeDestructuring
          if !namespace
            [name]
          elsif namespace.const_type?
            [*const_name(namespace), name]
          elsif namespace.lvar_type? || namespace.cbase_type?
            [nil, name]
          end
        end
```
What is `node.source` and what is the `namespace`?

**Comment by pirj** [comment]
> MyClass is Namespace1::Namespace2::Namespace3::MyClass ?

I find it puzzling to answer this question.

**Comment by pirj** [comment]
We need clear directions, @CaptainPhilipp

**Comment by pirj** [comment]
Can you please provide the information necessary to investigate the root cause @CaptainPhilipp ?

**Comment by pirj** [comment]
No clear reproduction example.

Please feel free to reopen and provide more information.
