### ISSUE TITLE
RSpec/FactoryBot/CreateList: undefined method `to_sym' for nil:NilClass

### ISSUE THREAD

**Issue by leoarnold** [rubocop-hq/rubocop-rspec#1066]
In a project with the configuration

```yaml
# .rubocop.yml
---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 144

Metrics/BlockLength:
  Exclude:
  - '*.gemspec'

Naming/FileName:
  Exclude:
  - '*.gemspec'

Style/Documentation:
  Enabled: false

Style/StringConcatenation:
  Enabled: false
```

and

```yaml
# spec/.rubocop.yml
---
inherit_from: ../.rubocop.yml

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/NotToNot:
  EnforcedStyle: to_not
```

with the test file

```ruby
# spec/test.rb

# frozen_string_literal: true

module WebMock
  module API
    module_function

    def reset_executed_requests!
      WebMock::RequestRegistry.instance.reset!
    end
  end
end
```

and the versions

```
RuboCop 1.0.0 (using Parser 2.7.2.0, rubocop-ast 1.1.0, running on ruby 2.6.6 x86_64-linux)
```

I get the error

```
$ rubocop -d spec/test.rb 
For /home/user/myproject: configuration from /home/user/myproject/.rubocop.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-rspec-1.42.0/config/default.yml
configuration from /home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-rspec-1.42.0/config/default.yml
Default configuration from /home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/config/default.yml
Inspecting 1 file
Scanning /home/user/myproject/spec/test.rb
For /home/user/myproject/spec: configuration from /home/user/myproject/spec/.rubocop.yml
Inheriting configuration from /home/user/myproject/.rubocop.yml
AllCops/Exclude configuration from /home/user/myproject/.rubocop.yml
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:5:4.
undefined method `to_sym' for nil:NilClass
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/mixin/configurable_enforced_style.rb:69:in `style'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-rspec-1.42.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:61:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:152:in `investigate_partial'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:122:in `process_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `reduce'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:47:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command.rb:11:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:65:in `run_command'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:41:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:13:in `block in <top (required)>'
/home/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:12:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `load'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `<main>'
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:8:6.
undefined method `to_sym' for nil:NilClass
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/mixin/configurable_enforced_style.rb:69:in `style'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-rspec-1.42.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:61:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:153:in `on_def'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:152:in `investigate_partial'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:122:in `process_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `reduce'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:47:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command.rb:11:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:65:in `run_command'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:41:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:13:in `block in <top (required)>'
/home/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:12:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `load'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `<main>'
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:8:6.
undefined method `to_sym' for nil:NilClass
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/mixin/configurable_enforced_style.rb:69:in `style'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-rspec-1.42.0/lib/rubocop/cop/rspec/factory_bot/create_list.rb:61:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:158:in `block in on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:155:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:155:in `each_with_index'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:155:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_send'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:153:in `on_def'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_def'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `block in on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:136:in `on_dstr'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:137:in `on_while'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-ast-1.1.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:152:in `investigate_partial'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:122:in `process_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `reduce'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/runner.rb:47:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/command.rb:11:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:65:in `run_command'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/lib/rubocop/cli.rb:41:in `run'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:13:in `block in <top (required)>'
/home/user/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/gems/rubocop-1.0.0/exe/rubocop:12:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `load'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/rubocop:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.6@givve-api/bin/ruby_executable_hooks:24:in `<main>'
.

1 file inspected, no offenses detected

3 errors occurred:
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:5:4.
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:8:6.
An error occurred while RSpec/FactoryBot/CreateList cop was inspecting /home/user/myproject/spec/test.rb:8:6.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
1.0.0 (using Parser 2.7.2.0, rubocop-ast 1.1.0, running on ruby 2.6.6 x86_64-linux)
Finished in 0.7506606329989154 seconds
```

**Comment by pirj** [comment]
Thanks for the detailed report.
Unfortunately, RuboCop-RSpec 1.x is not compatible with RuboCop 1.0. I [suggest you use](https://github.com/rubocop-hq/rubocop-rspec/issues/1051#issuecomment-714723918) [2.0.0.pre](https://rubygems.org/gems/rubocop-rspec/versions/2.0.0.pre) and follow the releases of RuboCop-RSpec, we're [working hard on the final 2.0.0 version](https://github.com/rubocop-hq/rubocop-rspec/pull/1055).

**Comment by pirj** [comment]
JFYI, [2.0](https://github.com/rubocop-hq/rubocop-rspec/releases/tag/v2.0.0) has been released.
