### ISSUE TITLE
RSpec/ExpectActual lead into infinite-loop with rubocop -A

### ISSUE THREAD

**Issue by Bartuz** [rubocop-hq/rubocop-rspec#1092]
Hello.

running such spec:

```
# frozen_string_literal: true

require 'spec_helper'

describe "Infinite loop lets goooooo" do
  subject(:call) { true }

  it 'goes into infinite loop with rubocop -A' do
    expect(:call).to eq(true)
  end
end
```

with `rubocop -A` option causes infinite loop (and providing false `[Corrected]` message when in reality nothing was corrected.

Here is console output 

```
Inspecting 1 file
C

Offenses:

test_spec.rb:9:12: C: [Corrected] RSpec/ExpectActual: Provide the actual you are testing to expect(...).
    expect(:call).to eq(true)
           ^^^^^

0 files inspected, 1 offense detected, 1 offense corrected
Infinite loop detected in /Users/bartuz/test_spec.rb and caused by RSpec/ExpectActual -> RSpec/ExpectActual
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:304:in `check_for_infinite_loop'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:287:in `block in iterate_until_no_changes'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:286:in `loop'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:132:in `block in file_offenses'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:157:in `file_offense_cache'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:131:in `file_offenses'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:122:in `process_file'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:100:in `each'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:100:in `reduce'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/runner.rb:47:in `run'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli/command.rb:11:in `run'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli/environment.rb:18:in `run'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli.rb:65:in `run_command'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/lib/rubocop/cli.rb:41:in `run'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/exe/rubocop:13:in `block in <top (required)>'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/bartuz/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-0.93.1/exe/rubocop:12:in `<top (required)>'
/Users/bartuz/.asdf/installs/ruby/2.7.2/bin/rubocop:23:in `load'
/Users/bartuz/.asdf/installs/ruby/2.7.2/bin/rubocop:23:in `<main>'
```

**Comment by Darhazer** [comment]
That happens because we have a literal in both sides. It should not attempt to correct in this case. I'd say it should not even raise an offense, though having a test that compares a literal to another literal doesn't make sense. Maybe the same cop should flag the issue but with another message?

**Comment by pirj** [comment]
Interesting case, thanks for reporting!

You should be looking around here https://github.com/rubocop-hq/rubocop-rspec/blob/78f94bb3216fa2a6f27a43af47728762caabde89/lib/rubocop/cop/rspec/expect_actual.rb#L62

This message sounds reasonable to me:

> Provide the actual you are testing

however, swapping two literals doesn't make sense.
You may throw in something like:
```ruby
next if literal?(expected)
```
and add a spec for this case (and a changelog entry proclaiming yourself as a victor against this nasty issue).
Pull request is welcome!
