### ISSUE TITLE
RSpec/LeadingSubject undefined method `body' for nil:NilClass

### ISSUE THREAD

**Issue by mwolman** [rubocop-hq/rubocop-rspec#1118]
I created a new `.rubocop.yml` file inside `spec/support/shared_context/`. This is how it looks:

```yaml
inherit_from: ../../../.rubocop.yml

RSpec/ContextWording:
  Enabled: false
```

I have one file placed in this folder apart from the `.rubocop.yml` file called `request_initializer.rb`:

```ruby
module RequestInitializer
  extend RSpec::SharedContext

  subject { response }

  before { |example| request! unless example.metadata[:skip_before] }
end
```

I'm creating the shared context in this way to be able to require the module in my `rails_helper.rb`. When running `rubocop` I'm getting this error:

```
.Scanning /Users/micaela/Documents/rails-api-boilerplate/spec/support/shared_context/requests_initializer.rb
For /Users/micaela/Documents/rails-api-boilerplate/spec/support/shared_context: configuration from /Users/micaela/Documents/rails-api-boilerplate/spec/support/shared_context/.rubocop.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/.rubocop.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/.rubocop_todo.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/rubocop/rubocop_rails.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/rubocop/rubocop_rspec.yml
AllCops/Exclude configuration from /Users/micaela/Documents/rails-api-boilerplate/.rubocop.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/.rubocop_todo.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/rubocop/rubocop_rails.yml
Inheriting configuration from /Users/micaela/Documents/rails-api-boilerplate/rubocop/rubocop_rspec.yml
An error occurred while RSpec/LeadingSubject cop was inspecting /Users/micaela/Documents/rails-api-boilerplate/spec/support/shared_context/requests_initializer.rb:4:2.
undefined method `body' for nil:NilClass
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-rspec-2.1.0/lib/rubocop/cop/rspec/leading_subject.rb:65:in `parent'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-rspec-2.1.0/lib/rubocop/cop/rspec/leading_subject.rb:57:in `offending_node'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-rspec-2.1.0/lib/rubocop/cop/rspec/leading_subject.rb:46:in `check_previous_nodes'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-rspec-2.1.0/lib/rubocop/cop/rspec/leading_subject.rb:42:in `on_block'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:98:in `each'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:69:in `on_block'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `block in on_dstr'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `each'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:137:in `on_dstr'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:71:in `on_begin'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:138:in `on_while'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:71:in `on_module'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-ast-1.4.0/lib/rubocop/ast/traversal.rb:20:in `walk'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cop/team.rb:83:in `investigate'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:315:in `inspect_file'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:286:in `loop'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:132:in `block in file_offenses'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:157:in `file_offense_cache'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:131:in `file_offenses'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:122:in `process_file'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:100:in `each'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:100:in `reduce'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:86:in `inspect_files'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/runner.rb:47:in `run'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/command/execute_runner.rb:26:in `block in execute_runner'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/command/execute_runner.rb:52:in `with_redirect'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/command.rb:11:in `run'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli/environment.rb:18:in `run'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli.rb:65:in `run_command'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli.rb:72:in `execute_runners'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/lib/rubocop/cli.rb:41:in `run'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/exe/rubocop:13:in `block in <top (required)>'
/Users/micaela/.rvm/rubies/ruby-2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/Users/micaela/.rvm/gems/ruby-2.7.2/gems/rubocop-1.8.1/exe/rubocop:12:in `<top (required)>'
/Users/micaela/.rvm/gems/ruby-2.7.2/bin/rubocop:23:in `load'
/Users/micaela/.rvm/gems/ruby-2.7.2/bin/rubocop:23:in `<main>'
/Users/micaela/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `eval'
/Users/micaela/.rvm/gems/ruby-2.7.2/bin/ruby_executable_hooks:24:in `<main>'
```

Details:
```
1.8.1 (using Parser 3.0.0.0, rubocop-ast 1.4.0, running on ruby 2.7.2 x86_64-darwin19)
```

**Comment by pirj** [comment]
Thanks for the report.

I would suggest defining this shared context as:
```ruby
# spec/support/shared_context/request_initializer.rb
RSpec.shared_context 'request initializer' do
  subject { response }

  before { |example| request! unless example.metadata[:skip_before] }
end
```
and include it in the config:
```ruby
RSpec.configuration do |config|
  config.include_context 'request initializer', type: :request
end
```

`rubocop-rspec` is not capable of working with modules that act as example groups, only with RSpec DSL.
One way around this is to exclude the directory with shared contexts from inspection.

Support of such syntax is not planned.

**Comment by mwolman** [comment]
@pirj thank you! I didn't know that I can include the context in that way, it worked

**Comment by pirj** [comment]
You're always welcome, @mwolman !
