### ISSUE TITLE
Error occurred while RSpec/OverwritingSetup cop was inspecting

### ISSUE THREAD

**Issue by microweb10** [rubocop-hq/rubocop-rspec#742]
Hi 😄 

I don't know if you are aware of this, I'm posting it just in case you don't.

If you have a `let` declaration in a spec containing an extra space like this:
```
let (:user) { create(:user) }
```

Your tests will pass, but rubocop will raise an exception like this:
```
Scanning /Users/microweb10/rubocop_test/spec/models/user_spec.rb
An error occurred while RSpec/OverwritingSetup cop was inspecting /Users/microweb10/rubocop_test/spec/models/user_spec.rb:3:0.
undefined method `value' for "s(:begin,\n  s(:sym, :author))":RuboCop::AST::Node
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:51:in `block in find_duplicates'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/node.rb:185:in `block in each_child_node'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/node.rb:183:in `each'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/node.rb:183:in `each_child_node'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:47:in `find_duplicates'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-rspec-1.26.0/lib/rubocop/cop/rspec/overwriting_setup.rb:34:in `on_block'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:44:in `block (2 levels) in on_block'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:109:in `with_cop_error_handling'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:43:in `block in on_block'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:42:in `each'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:42:in `on_block'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/traversal.rb:49:in `block in on_begin'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/traversal.rb:49:in `each'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/traversal.rb:49:in `on_begin'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:48:in `on_begin'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/ast/traversal.rb:12:in `walk'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/commissioner.rb:60:in `investigate'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/team.rb:114:in `investigate'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/team.rb:102:in `offenses'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:259:in `inspect_file'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:206:in `block in do_inspection_loop'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:238:in `block in iterate_until_no_changes'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:231:in `loop'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:231:in `iterate_until_no_changes'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:202:in `do_inspection_loop'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:111:in `block in file_offenses'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:121:in `file_offense_cache'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:109:in `file_offenses'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:100:in `process_file'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:78:in `block in each_inspected_file'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:75:in `each'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:75:in `reduce'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:75:in `each_inspected_file'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:67:in `inspect_files'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/runner.rb:39:in `run'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cli.rb:156:in `execute_runner'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cli.rb:84:in `execute_runners'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/lib/rubocop/cli.rb:41:in `run'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/bin/rubocop:13:in `block in <top (required)>'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/Users/microweb10/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rubocop-0.54.0/bin/rubocop:12:in `<top (required)>'
/Users/microweb10/.rbenv/versions/2.3.2/bin/rubocop:22:in `load'
/Users/microweb10/.rbenv/versions/2.3.2/bin/rubocop:22:in `<main>'
.

1 file inspected, no offenses detected
```
rubocop (0.54.0)
rubocop-rspec (1.26.0)
rspec-core (3.8.0)

**Comment by dgollahon** [comment]
Hi @microweb10. I'm was unable to reproduce this on the current version of `rubocop-rspec`. Could you try the latest version and see if you still get the error and/or provide a reproduction test file? Thanks!

I seem to recall a fix going out for this at some point, but I can't seem to find the issue/PR at the moment if it does, in fact, exist.

**Comment by microweb10** [comment]
Hi @dgollahon!

Thanks for the update ☺️ 

You are right! 🎉 

My apologies for the inconvenience. 🙏 

 Closing issue. 😃

**Comment by dgollahon** [comment]
No worries, glad it works as expected for you.
