### ISSUE TITLE
Without require: false, rubocop-rspec will cause crash

### ISSUE THREAD

**Issue by gbudiman** [rubocop-hq/rubocop-rspec#749]
Hopefully it will save time, but without `require: false` in `Gemfile`, the following crash will occur. Happened to both ruby 2.6.0 and 2.6.2.
```/Users/gbudiman/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:86: [BUG] Segmentation fault at 0x0000000109345a3a
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0003 p:---- s:0011 e:000010 CFUNC  :sleep
c:0002 p:0025 s:0006 e:000005 BLOCK  /Users/gbudiman/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:86 [FINISH]
c:0001 p:---- s:0003 e:000002 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/gbudiman/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:86:in `block (2 levels) in timeout'
/Users/gbudiman/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/timeout.rb:86:in `sleep'```

**Comment by pirj** [comment]
Is this it? Can you provide more context? Is this all of the output? What command are you running?
Can you create a minimal all that allows to reproduce the issue and share it?

**Comment by sAnti09** [comment]
Also had this bug. Running rspec tests produce the error reported above. There are cases wherein the bug doesn't occur but only on rare occasions.

I'm running on MacOs. 
```
Process:               ruby [24888]
Path:                  /Users/USER/*/ruby
Identifier:            ruby
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ruby [6044]
Responsible:           ruby [24888]

Date/Time:             2019-06-10 17:46:18.554 +0800
OS Version:            Mac OS X 10.14.5 (18F132)
System Integrity Protection: enabled
Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000104e3ea3a
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x104e3ea3a:
    __LINKEDIT             0000000104e3c000-0000000104e3e000 [    8K] r--/rwx SM=COW  /Users/USER/*/digest.bundle
-->
    MALLOC_LARGE           0000000104e56000-0000000104e7a000 [  144K] rw-/rwx SM=PRV

Application Specific Information:
crashed on child side of fork pre-exec
```

**Comment by bquorning** [comment]
Again, could you create a minimal app that allows to reproduce the issue and share it? It’s hard to debug this issue just from an OS error message

**Comment by pirj** [comment]
Can you provide some reproducible scenario, @gbudiman @sAnti09 ? Something involving ruby version installation and a repository that crashes would do.
