### ISSUE TITLE
error .. RSpec/DescribedClass cop was inspecting .. describe(CONSTANT)

### ISSUE THREAD

**Issue by jaredbeck** [rubocop-hq/rubocop-rspec#799]
Upgrading PaperTrail from 1.33.0 to 1.35.0, got this error:

```
An error occurred while RSpec/DescribedClass cop was 
inspecting .../spec/paper_trail/version_number_spec.rb:6:2.
```

In [`version_number_spec.rb`](https://github.com/paper-trail-gem/paper_trail/blob/da9c743831ff7b948680ee0ef847ad8516f1a206/spec/paper_trail/version_number_spec.rb) our `described_class` is a module named `VERSION`. 🤔 I admit, it's unusual (I didn't name it) but I think we can agree that rubocop should not crash :smile:

```
module PaperTrail
  ::RSpec.describe VERSION do
    describe "STRING" do
      it "joins the numbers into a period separated string" do
        expect(described_class::STRING).to eq(
          ...
```

Please see also [paper_trail/version_number.rb](https://github.com/paper-trail-gem/paper_trail/blob/da9c743831ff7b948680ee0ef847ad8516f1a206/lib/paper_trail/version_number.rb) if necessary.

I'm happy to work on this issue if someone can point me in the right direction. :heart:

**Comment by jaredbeck** [comment]
Stack trace

```
An error occurred while RSpec/DescribedClass cop was inspecting /Users/jared/git/paper-trail-gem/paper_trail/spec/paper_trail/version_number_spec.rb:6:2.
undefined method `first' for nil:NilClass
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:147:in `collapse_namespace'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:132:in `full_const_name'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:128:in `offensive_described_class?'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:114:in `offensive?'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:80:in `find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:85:in `block in find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:193:in `block in each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/node.rb:190:in `each_child_node'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:84:in `find_usage'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-rspec-1.35.0/lib/rubocop/cop/rspec/described_class.rb:61:in `on_block'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:57:in `block (2 levels) in trigger_responding_cops'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:128:in `with_cop_error_handling'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:56:in `block in trigger_responding_cops'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:55:in `trigger_responding_cops'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:32:in `block (2 levels) in <class:Commissioner>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:150:in `on_while'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `block in on_begin'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:50:in `on_begin'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:33:in `block (2 levels) in <class:Commissioner>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/ast/traversal.rb:13:in `walk'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/commissioner.rb:44:in `investigate'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:119:in `investigate'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:107:in `offenses'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cop/team.rb:44:in `inspect_file'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:277:in `inspect_file'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:225:in `block in do_inspection_loop'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:257:in `block in iterate_until_no_changes'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `loop'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:250:in `iterate_until_no_changes'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:221:in `do_inspection_loop'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:124:in `block in file_offenses'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:142:in `file_offense_cache'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:122:in `file_offenses'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:110:in `process_file'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:87:in `block in each_inspected_file'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `reduce'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:86:in `each_inspected_file'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:73:in `inspect_files'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:39:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:210:in `execute_runner'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:80:in `execute_runners'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:51:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/exe/rubocop:13:in `block in <top (required)>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/exe/rubocop:12:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/bin/rubocop:23:in `load'
/Users/jared/.rbenv/versions/2.6.3/bin/rubocop:23:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/jared/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
```

**Comment by bquorning** [comment]
@pirj Would you have time to look at this bug report, too?

**Comment by pirj** [comment]
Thanks for the detailed report!
It's reproducible, let me take a stab on the fix.

**Comment by pirj** [comment]
Fixed, now I'll have to find a way to fit it into our hard constraints.
```
lib/rubocop/cop/rspec/described_class.rb:35:7: C: Metrics/ClassLength: Class has too many lines. [104/100]
      class DescribedClass < Cop ...
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jaredbeck** [comment]
> .. cop/rspec/described_class.rb .. Metrics/ClassLength .. Class has too many lines. [104/100]

I'm new to this codebase, so take this with a grain of salt, but I think 100 lines is not practical.  RuboCop itself [currently has a ClassLength of 174](https://github.com/rubocop-hq/rubocop/blob/master/.rubocop_todo.yml#L19). In the past, [they've been above 200](https://github.com/rubocop-hq/rubocop/blame/9e76387952725f1a7fa54989024114549c0b7d80/.rubocop_todo.yml#L16).

**Comment by pirj** [comment]
I agree though those limits tend to grow, and keeping them tight is a way to sit back and think what can be improved. Be it the future author of the code, or an encounter attempting to fix or improve it, it's hard to grasp more than 100 lines of code (excluding empty lines and comments).
I had this thing in this very repository, I've been returning to my pull request several times doing month-long breaks, and it was extremely hard to understand the code.

A problem with cops is that it's not a part of the system, it's a self-contained unit using the extension API provided by RuboCop, you usually can't push complexity out of it.

One exception enforced styles, it's sometimes two cops in one, performing code analysis that may not have common parts. However, we don't have a concept for mutually exclusive cops that would be called depending on the enforced styles, but that could help making the cops more focused.

**Comment by pirj** [comment]
[174](https://github.com/rubocop-hq/rubocop/blob/master/.rubocop_todo.yml#L20) is in RuboCop's `.rubocop_todo.yml`, e.g. it's something that will be eventually addressed, and it appeared as a compromise of development effort to delivering new features/cops.
There's always a lack of resources and demand for new features, so this tradeoff is reasonable considering that some common parts of cops are being extracted, and that reduces their length and complexity.
